[2024-05-14T07:29:39.379+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-14T07:29:39.393+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_jobs104.data_crawler_list manual__2024-05-14T07:29:38.068071+00:00 [queued]>
[2024-05-14T07:29:39.397+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_jobs104.data_crawler_list manual__2024-05-14T07:29:38.068071+00:00 [queued]>
[2024-05-14T07:29:39.397+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-14T07:29:39.403+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_crawler_list> on 2024-05-14 07:29:38.068071+00:00
[2024-05-14T07:29:39.406+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=403) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-14T07:29:39.407+0000] {standard_task_runner.py:63} INFO - Started process 405 to run task
[2024-05-14T07:29:39.407+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_jobs104', 'data_crawler_list', 'manual__2024-05-14T07:29:38.068071+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/data_pipeline_jobs104-checkpoint.py', '--cfg-path', '/tmp/tmpawv2rawf']
[2024-05-14T07:29:39.409+0000] {standard_task_runner.py:91} INFO - Job 47: Subtask data_crawler_list
[2024-05-14T07:29:39.434+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_jobs104.data_crawler_list manual__2024-05-14T07:29:38.068071+00:00 [running]> on host 9bf348f884a5
[2024-05-14T07:29:39.475+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_jobs104' AIRFLOW_CTX_TASK_ID='data_crawler_list' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T07:29:38.068071+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-14T07:29:38.068071+00:00'
[2024-05-14T07:29:39.476+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-14T07:29:39.483+0000] {logging_mixin.py:188} INFO - 設定排除44家公司
[2024-05-14T07:29:39.484+0000] {logging_mixin.py:188} INFO - test
[2024-05-14T07:29:41.526+0000] {logging_mixin.py:188} INFO - url: https://www.104.com.tw/jobs/search/?ro=1&keyword=%E5%BE%8C%E7%AB%AF%E5%B7%A5%E7%A8%8B%E5%B8%AB+python&isnew=3&jobexp=1%2C3&mode=l&order=16&asc=0
[2024-05-14T07:29:41.528+0000] {logging_mixin.py:188} INFO - 執行錯誤, retry 1, Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2024-05-14T07:29:42.790+0000] {logging_mixin.py:188} INFO - url: https://www.104.com.tw/jobs/search/?ro=1&keyword=%E5%BE%8C%E7%AB%AF%E5%B7%A5%E7%A8%8B%E5%B8%AB+python&isnew=3&jobexp=1%2C3&mode=l&order=16&asc=0
[2024-05-14T07:29:42.790+0000] {logging_mixin.py:188} INFO - 執行錯誤, retry 2, Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2024-05-14T07:29:43.983+0000] {logging_mixin.py:188} INFO - url: https://www.104.com.tw/jobs/search/?ro=1&keyword=%E5%BE%8C%E7%AB%AF%E5%B7%A5%E7%A8%8B%E5%B8%AB+python&isnew=3&jobexp=1%2C3&mode=l&order=16&asc=0
[2024-05-14T07:29:43.984+0000] {logging_mixin.py:188} INFO - 執行錯誤, retry 3, Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2024-05-14T07:29:43.984+0000] {logging_mixin.py:188} INFO - 達到重試上限，放棄爬取
[2024-05-14T07:29:43.985+0000] {logging_mixin.py:188} INFO - 過濾剩0筆資料 | 花費 4.5 秒
[2024-05-14T07:29:43.986+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-14T07:29:43.986+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-14T07:29:43.990+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_pipeline_jobs104, task_id=data_crawler_list, run_id=manual__2024-05-14T07:29:38.068071+00:00, execution_date=20240514T072938, start_date=20240514T072939, end_date=20240514T072943
[2024-05-14T07:29:44.011+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-14T07:29:44.025+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-14T07:29:44.026+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
