[2024-05-14T08:02:04.560+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-14T08:02:04.569+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_jobs104.data_warehouse manual__2024-05-14T08:01:54.539823+00:00 [queued]>
[2024-05-14T08:02:04.572+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_jobs104.data_warehouse manual__2024-05-14T08:01:54.539823+00:00 [queued]>
[2024-05-14T08:02:04.573+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-14T08:02:04.577+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_warehouse> on 2024-05-14 08:01:54.539823+00:00
[2024-05-14T08:02:04.580+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=92) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-14T08:02:04.581+0000] {standard_task_runner.py:63} INFO - Started process 94 to run task
[2024-05-14T08:02:04.581+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_jobs104', 'data_warehouse', 'manual__2024-05-14T08:01:54.539823+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_jobs104.py', '--cfg-path', '/tmp/tmp5y4ulc1h']
[2024-05-14T08:02:04.582+0000] {standard_task_runner.py:91} INFO - Job 65: Subtask data_warehouse
[2024-05-14T08:02:04.602+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_jobs104.data_warehouse manual__2024-05-14T08:01:54.539823+00:00 [running]> on host ceeaa83f1981
[2024-05-14T08:02:04.637+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_jobs104' AIRFLOW_CTX_TASK_ID='data_warehouse' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T08:01:54.539823+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-14T08:01:54.539823+00:00'
[2024-05-14T08:02:04.638+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-14T08:02:04.644+0000] {logging_mixin.py:188} INFO - data_warehouse !!!
[2024-05-14T08:02:04.644+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-14T08:02:04.644+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-14T08:02:04.648+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_pipeline_jobs104, task_id=data_warehouse, run_id=manual__2024-05-14T08:01:54.539823+00:00, execution_date=20240514T080154, start_date=20240514T080204, end_date=20240514T080204
[2024-05-14T08:02:04.685+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-14T08:02:04.693+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-14T08:02:04.693+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
